version: '2'

services:
    web:
        build: .
        volumes:
            - /srv/http/config/wim/default.conf:/etc/nginx/conf.d/default.conf
            - /srv/http/share/wim:/usr/share/nginx/html
        ports:
            - 8001:80

