services:
    http-server:
        build: .
        container_name: http-wim-server
        volumes:
            - /srv/http/wim/config/default.conf:/etc/nginx/conf.d/default.conf
            - /srv/http/share/wim:/usr/share/nginx/html
        ports:
            - 8180:80
        restart: always
