services:
    http-server:
        build: .
        volumes:
            - /srv/http/iso/config/default.conf:/etc/nginx/conf.d/default.conf
            - /home/iso/share/iso:/usr/share/nginx/html
        ports:
            - 8080:80
        restart: always
